/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "AWS REGION>",
    "aws_cognito_identity_pool_id": "<AWS ID POOL>",
    "aws_cognito_region": "<AWS REGION>",
    "aws_user_pools_id": "<AWS ID>",
    "aws_user_pools_web_client_id": "<AWS ID>",
    "oauth": {},
    "aws_cloud_logic": "enable",
    "aws_cloud_logic_custom": [
        {
            "name": "<AWS NAME>",
            "endpoint": "<AWS ENDPOINT>",
            "region": "<AWS REGION>"
        }
    ]
};


export default awsmobile;
