/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    // "aws_cognito_identity_pool_id": "<AWS ID POOL ID GOES HERE>",
    // "aws_cognito_region": "<AWS REGION GOES HERE>",
    // "aws_user_pools_id": "<AWS USER POOLS ID GOES HERE>",
    // "aws_user_pools_web_client_id": "<AWS WEBCLIENT ID GOES HERE>",
    "oauth": {},
    "aws_cloud_logic": "enable",
    "aws_cloud_logic_custom": [
        {
            "name": "asetuapipoc",
            // "endpoint": "<AWS ENDPOINT GOES HERE>",
            "region": "ap-south-1"
        }
    ]
};


export default awsmobile;